- name: install apache2 server
  tags: web, apache2
  apt:
    name: apache2
    state: present

- name: start apache2 service
  tags: web, apache2
  service:
    name: apache2
    state: started
    enabled: yes

- name: copy html files
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644