Vagrant.configure("2") do |config|
config.ssh.insert_key = false
#no need to customize memory for docker

    # Application server 1
    config.vm.define "app1" do |app|
        app.vm.hostname = "app1.dev"
        app.vm.provider :docker do |d|
            d.build_dir = "./app1" # Path to Dockerfile
            d.remains_running = true
            d.has_ssh = true
            #custom network
            d.create_args = ["--network", "nw-ansi", "--ip", "192.168.60.4"]
        end
    end

    # Application server 2
    config.vm.define "app2" do |app|
        app.vm.hostname = "app2.dev"
        app.vm.provider :docker do |d|
            d.build_dir = "./app2" # Path to Dockerfile
            d.remains_running = true
            d.has_ssh = true
            #custom network
            d.create_args = ["--network", "nw-ansi", "--ip", "192.168.60.5"]
        end
    end

    # Database server
    config.vm.define "db" do |db|
        db.vm.hostname = "db.dev"
        db.vm.provider :docker do |d|
            d.build_dir = "./db" # Path to Dockerfile
            d.remains_running = true
            d.has_ssh = true
            #custom network
            d.create_args = ["--network", "nw-ansi", "--ip", "192.168.60.6"]
        end
    end
end