---
- hosts: all
  become: yes
  
  pre-tasks:
    - name: Update apt repository cache
      apt:
        update_cache: yes

- hosts: app1
  become: yes
  roles:
    - base
    - web_server

- hosts: app2
  become: yes
  roles:
    - base
    - db_server
