---
- name: Install Apache on app1 and Nginx on app2
  hosts: all
  become: yes

  tasks:
    # Install Apache on app1
    - name: Install Apache HTTP Server on app1
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: inventory_hostname == 'app1'

    # Start and enable Apache on app1
    - name: Ensure Apache is started and enabled on app1
      service:
        name: apache2
        state: started
        enabled: yes
      when: inventory_hostname == 'app1'

    # Install Nginx on app2
    - name: Install Nginx on app2
      apt:
        name: nginx
        state: present
        update_cache: yes
      when: inventory_hostname == 'app2'

    # Start and enable Nginx on app2
    - name: Ensure Nginx is started and enabled on app2
      service:
        name: nginx
        state: started
        enabled: yes
      when: inventory_hostname == 'app2'
