---
- hosts: all
  become: yes

  vars:
    app_location: /home/vagrant/my-node-app 
    app_start_script: /home/vagrant/my-node-app/app.js  

  tasks:
    - name: Update apt repository cache
      apt:
        update_cache: yes

    - name: Install prerequisites
      apt:
        name:
          - curl
          - build-essential
          - libssl-dev
        state: present

    - name: Install Node.js
      apt:
        name: nodejs
        state: present

    - name: Install npm
      apt:
        name: npm
        state: present

    - name: Verify Node.js installation
      command: node -v
      register: node_version
      changed_when: false
      failed_when: node_version.stdout is not defined

    - name: Verify npm installation
      command: npm -v
      register: npm_version
      changed_when: false
      failed_when: npm_version.stdout is not defined

    - name: Install forever globally
      npm:
        name: forever
        global: yes

    - name: Ensure the Node.js application directory exists
      file: "path={{ app_location }} state=directory"

    - name: Copy the Node.js application to the server
      copy:
        src: "app.js", "package.json"
        dest: "{{ app_location }}"
        
    - name: Install the Node.js application dependencies
      npm: path="{{ app_location }}"
      

    - name: Start Node.js application with forever
      command: "forever start {{ app_location }}/app.js"
      args:
        chdir: "{{ app_location }}"
